### ISSUE TITLE
assimp/importer.hpp: No such file or directory

### ISSUE THREAD

**Issue by romanlevin** [Polytonic/Glitter#1]
```
In file included from /home/roman/dev/opengl/Glitter/Glitter/Sources/main.cpp:2:0:
/home/roman/dev/opengl/Glitter/Glitter/Headers/glitter.hpp:5:31: fatal error: assimp/importer.hpp: No such file or directory
 #include <assimp/importer.hpp>
                               ^
compilation terminated.
make[2]: *** [CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Glitter.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Polytonic** [comment]
Did you remember to pull down all the submodules? 

From your directory structure it looks like you're running some flavor of Linux. Which distribution?  I can try to repro later this week.

**Comment by romanlevin** [comment]
I'm running Linux Mint 17.1.

I used the `--recursive` flag when cloning the repo.

Everything was built successfully (including `assimp`); failure only occurs when building `main.cpp`.

Thanks for looking into this.

**Comment by Polytonic** [comment]
Can you provide an exact list of commands you entered into your shell?

I can try this on a Debian machine later. It's not Mint but reasonably close enough for now.

**Comment by romanlevin** [comment]
```shell
> git clone --recursive https://github.com/Polytonic/Glitter
> cd Glitter/Build
> cmake ..
> make
```

**Comment by Polytonic** [comment]
Currently trying to track down a Linux box to try building on, but in the meantime, can you confirm that the `<assimp/Importer.hpp>` header actually exists? It should be a file you can open and look at. 

Random speculation: maybe Linux is picky about case-sensitivity in filenames?

**Comment by romanlevin** [comment]
:+1:  Yes, it was a case sensitivity issue.

Honestly I should have figured it out myself, since it was pretty clear Glitter was written on an OS X box. I'll have a pull request fixing this ready in a moment.
