### ISSUE TITLE
No CMAKE_C_COMPILER could be found.

### ISSUE THREAD

**Issue by callmeStriking** [Polytonic/Glitter#14]
Do I need to set this beforehand? I would assume it just looks for `cc` and `cxx`, which are present on my system...

```
Robs-MacBook-Pro:Build rob$ cmake -G "Xcode" ..
-- The C compiler identification is AppleClang 6.1.0.6020053
-- The CXX compiler identification is AppleClang 6.1.0.6020053
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "/Volumes/Macintosh HD/rob/dev/Glitter/Build/CMakeFiles/CMakeOutput.log".
```

**Comment by Polytonic** [comment]
This, I have never seen before.  What versions of CMake and OSX are you running?

**Comment by callmeStriking** [comment]
Mac OS 10.10.5 (14F27), cmake version 3.3.1

**Comment by Polytonic** [comment]
As a temporary work around you can just set CXX and CC manually. That
should work. I can investigate your problem more thoroughly after work.

On Sep 21, 2015, at 9:51 AM, Rob Stolarz <notifications@github.com> wrote:

Mac OS 10.10.5 (14F27), cmake version 3.3.1
> On Sep 21, 2015, at 12:49 PM, Kevin Fung <notifications@github.com> wrote:
>
> This, I have never seen before. What versions of CMake and OSX are you
running?
>
> —
> Reply to this email directly or view it on GitHub.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/Polytonic/Glitter/issues/14#issuecomment-142041004>.

**Comment by callmeStriking** [comment]
I figured it out.

You can't have spaces in the path to your compiler, or CMake dies.

Someone should really fix that.

Thanks!

**Comment by Polytonic** [comment]
> Someone should really fix that.

This sounds like a bug with CMake. Or at least, I don't think there's anything I can do to address or fix this. Sorry!
