### ISSUE TITLE
MinGW error -> 'realpath' was not declared in this scope

### ISSUE THREAD

**Issue by gdwhite** [Polytonic/Glitter#17]
I get the abovementioned error on line 142 in Vendor\assimp\code\DefaultIOSystem.cpp when compiling with MinGW 4.9.2 (i686-win32-dwarf-rev4, Built by MinGW-W64 project).

The fix was to make the following change on line 138 in that file:

```C++
//#ifdef _MSC_VER
#if defined(__MINGW32__) || defined(_MSC_VER)
```
so that it uses _fullpath instead of realpath.

**Comment by Polytonic** [comment]
This was fixed upstream by assimp [#660](https://github.com/assimp/assimp/issues/660). I will update the submodules again shortly.

**Comment by gdwhite** [comment]
Thanks Kevin.

I did not mean to imply that you were responsible for this issue/bug and I apologize if it came across that way.  In my tunnel vision in trying to solve this problem and lacking any other forum, I just quickly posted it in an attempt to be helpful to any who might be interested.

I'm really grateful (along with many others, I'm sure) to you for all of the work that you put into Glitter and the fact that it makes things so much easier.  I know that sometimes along with creating such a project comes all kinds of requests for support etc. that have the potential to be very irritating -- especially if coming from those who are unappreciative of the work involved.  I assure you that I'm definitely not in that camp and just want to be helpful in any way possible (to you and others).

Have you thought about creating a free Gitter chat room (https://gitter.im/) linked to this repository in order to provide a discussion forum for the project?  Here's an excerpt from the Wikipedia page (in case you're not familiar with it):

>"Individual chat rooms can be created for individual git repositories on GitHub. Chatroom privacy follows the privacy settings of the associated GitHub repository: thus, a chatroom for a private (i.e. members-only) GitHub repository is also private to those with access to the repository. A graphical badge linking to the chat room can then be placed in the git repository's README file, bringing it to the attention of all users and developers of the project. Users can chat in the chat rooms, or access private chat rooms for repositories they have access to, by logging in to Gitter via GitHub (which does not involve sharing the user's GitHub password with Gitter)."

**Comment by Polytonic** [comment]
> I know that sometimes along with creating such a project comes all kinds of requests for support etc. that have the potential to be very irritating

Oh, I'm happy to provide support. I just wanted to point out that if you report a problem here with one of the upstream dependencies, I'm just going to turn around and submit a bug report upstream. Might save you some time and effort to report it there and flag down my attention that a new version is needed. :smile: 

> Have you thought about creating a free Gitter chat room (https://gitter.im/) linked to this repository in order to provide a discussion forum for the project?

I'd rather not set up a Gitter chat room, at least, not right now. It's another thing I'd have to monitor. If you need real-time assistance, I normally sit in `##OpenGL` on Freenode. I can add a section to the readme to reflect that. You can also just open issues as well; I try to respond within 24 hours.

**Comment by gdwhite** [comment]
I definitely appreciate the support.

I should have been more specific about my suggestion regarding the Gitter chat room.  I was actually suggesting it as a community discussion forum that would encourage a lively discussion among users and hopefully relieve you of some of the support burden.  I do understand your reluctance to take on any other support burden but perhaps if you characterize it as a community discussion forum in Readme.md that would free you from feeling obligated to monitor it.  That's just my 2¢; I totally understand if you decide to pass on my suggestion.

**Comment by Polytonic** [comment]
There are about 500 stars on this repository. I very much doubt that there will be enough people who would congregate and "staff" a chat room like this for there to be consistent activity 24/7/365 with the domain expertise to actually help answer questions. You're much more likely to get immediate and relevant help in an established OpenGL chat support channel, such as ##OpenGL in Freenode IRC.
