### ISSUE TITLE
Error when executing ./Glitter on debian

### ISSUE THREAD

**Issue by jokoon** [Polytonic/Glitter#23]
Everything builds fine, I installed lXi6, and other package ending with -dev (I think it's the right thing, but I don't know which to install exactly).

I get 

Failed to Create OpenGL Context

**Comment by Polytonic** [comment]
1. What graphics card do you have?  
2. Have you installed your graphics card drivers? 
3. Is your graphics card OpenGL 4+ compatible?

**Comment by jokoon** [comment]
Intel HD Graphics 5500.

I installed debian 7, not sure if the graphic drivers were installed automatically, but I guess they did.

Don't tell me this is not compatible, this laptop is brand new.

And why should it be opengl 4+ compatible, opengl core is 3.3.

**Comment by Polytonic** [comment]
Glitter is configured for OpenGL 4.0 out of the box. If your card is not GL 4+ compatible, please change lines 16 and 17 in `main.cpp` to use OpenGL 3.3.

```c++
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
```

Some versions of the Linux Mesa driver are not GL 4 compatible if I remember correctly.

**Comment by jokoon** [comment]
I actually had the same problem with the learnopengl tutorials which uses 3.3.

I solved it by installing a backport driver.

Sorry to open such an issue for something which is unrelated.
