### ISSUE TITLE
Git says "SSL CA cert error"

### ISSUE THREAD

**Issue by binoaga** [Polytonic/Glitter#24]
Hello, I wanted to clone your git, and it gave me a certificate error. Should you update your cert or else? thanks.

**Comment by Polytonic** [comment]
This sounds like a problem with git or GitHub. I don't think it's related
to anything on my end.

On Jan 8, 2016, at 1:45 PM, binoaga <notifications@github.com> wrote:

Hello, I wanted to clone your git, and it gave me a certificate error
Should you update your cert or else? thanks

—
Reply to this email directly or view it on GitHub
<https://github.com/Polytonic/Glitter/issues/24>.

**Comment by Polytonic** [comment]
@binoaga please see [this GitHub help link](https://help.github.com/articles/error-ssl-certificate-problem-verify-that-the-ca-cert-is-ok/) for more information.  :smile:
