### ISSUE TITLE
glm/glc/matrix_transform.hpp: No such file or directory

### ISSUE THREAD

**Issue by WAFFO** [Polytonic/Glitter#25]
Hello,

I've been following the tutorial on [learnopengl.com](learnopengl.com) and got to a point where I needed to include the matrix transformation header in glm, but for some reason make cannot find it.

[Screenshot](http://i.imgur.com/h0dvjhm.png)

Also I just wanted to say thank you for making this. Every once in a while I try to set up OpenGL on my own, but I am still having trouble trying to deal with CMake files and finding out what libraries to install. I'm glad I have Glitter to practice with in the meantime.

**Comment by WAFFO** [comment]
Sorry, apparently there was a typo -.-

**Comment by Polytonic** [comment]
> Also I just wanted to say thank you for making this. Every once in a while I try to set up OpenGL on my own, but I am still having trouble trying to deal with CMake files and finding out what libraries to install. I'm glad I have Glitter to practice with in the meantime.

Sure thing! Let me know if you have any more problems. :smile:
