### ISSUE TITLE
Failed to Create OpenGL Context

### ISSUE THREAD

**Issue by gmaccarn** [Polytonic/Glitter#26]
I'm trying to get Glitter to work on Lubuntu, but am having trouble as far as creating the context. To my knowledge I have installed all the dependencies (OpenGL, X11, RandR to name a few) and cmake / make compile but I am still left with the "Failed to Create OpenGL Context" error message.

My cmake output code:
`-- Using X11 for window creation
-- Using GLX for context creation
-- Building a non-boost version of Assimp.
-- Looking for ZLIB...
-- checking for module 'zzip-zlib-config'
--   package 'zzip-zlib-config' not found
-- Found ZLIB: optimized;/usr/lib/x86_64-linux-gnu/libz.so;debug;/usr/lib/x86_64-linux-gnu/libz.so
-- checking for module 'minizip'
--   package 'minizip' not found
-- Enabled formats: 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X GLTF
-- Disabled formats:
OPENGL FOUND
/usr/lib/x86_64-linux-gnu/libGLU.so/usr/lib/x86_64-linux-gnu/libGL.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/majortom/Glitter/Build
`
My make output code:
`[  2%] Built target LinearMath
[  6%] Built target glfw
[ 50%] Built target assimp
[ 75%] Built target BulletCollision
[ 83%] Built target BulletDynamics
[ 83%] Built target Glitter
[ 91%] Built target Bullet3OpenCL_clew
[ 92%] Built target Bullet2FileLoader
[ 94%] Built target Bullet3Dynamics
[ 95%] Built target Bullet3Collision
[ 95%] Built target Bullet3Geometry
[ 96%] Built target Bullet3Common
[ 98%] Built target BulletInverseDynamics
[100%] Built target BulletSoftBody
` 

I have tried installing minizip and zzip-zlib-config to no avail. I have also tried different versions of OpenGL as specified by the closed issues (3.3 instead of 4.0). Is there something I'm missing?

**Comment by Polytonic** [comment]
What GPU do you have?

**Comment by gmaccarn** [comment]
I have an Intel HD Graphics 4000, but something that occurred to me is that I'm running Lubuntu through VirtualBox on Mac OS X. Is this the issue? I figured that since it's its own operating system it would be fine but that could be the problem.

**Comment by robstolarz** [comment]
You'll need to enable 3D acceleration in your VirtualBox config if you haven't already.

https://www.maketecheasier.com/enable-3d-acceleration-in-virtualbox/

**Comment by Polytonic** [comment]
I'm very fuzzy on Linux support, as I don't have a Linux dev machine. VMs ... doubly flaky, and I've never gotten around to fiddling with testing Glitter in one. 

Some cursory googling also brings up this ticket: https://www.virtualbox.org/ticket/12746

**Comment by gmaccarn** [comment]
I do have 3D acceleration enabled but I believe the ticket linked is the issue. I suppose I will have to use Bootcamp if I want to do this on Linux or just use Xcode. Thanks for the help!

**Comment by Polytonic** [comment]
I'm going to go ahead and close this issue then.  If you continue to have problems, feel free to open a new ticket, or reopen this one (if related). :smile:
