### ISSUE TITLE
We need more documentation

### ISSUE THREAD

**Issue by mro95** [Polytonic/Glitter#3]
Hi,

First of all I want to say that Glitter is a good idea for beginners, I'm also a beginner in OpenGL and I think it save a lot of time and struggle.
Only thing I miss is the documentation, I had to guess where I had to drop my files, and I don't know how to make a executable. So I had to use my own makefile: ``Make -f Makefile2``.
Can you explain it to me, so I can write documentation it?

**Comment by Polytonic** [comment]
Could you clarify what you mean by "drop my files"? The instructions should be pretty straightforward, copy-pasting into your shell. Did you follow the [Getting Started](https://github.com/Polytonic/Glitter#getting-started) steps? Note that `cmake` is *not* `make` (different binary). If you generate a makefile with `cmake`, the binary will be at `/Build/Glitter/Glitter`. Your headers go in `/Glitter/Headers/` and your source files go in `/Glitter/Sources/`. 

I started working on a "guide for complete newbies" a while ago, but that's on hold for at least a week, until I straighten things out. I'm all ears though, if you have suggestions for improvements?

**Comment by Polytonic** [comment]
@mro95 just want to follow up with this ... still having trouble?

**Comment by Polytonic** [comment]
Closing due to lack of response.

**Comment by mro95** [comment]
Hey, sorry for my late respone. I'm very busy so didn't test it, but it's clear for me now. thanks.
