### ISSUE TITLE
Compilation fail

### ISSUE THREAD

**Issue by hurrymomo** [Polytonic/Glitter#30]
Hi there
Sorry for asking a silliy question,but I am using Mac 10.11.6. I clone the repository from https://github.com/Polytonic/G.... However when I was trying to type 
cmake -G "Xcode" ..
The following error occurs,Can anyone help me?

CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineSystem.cmake:177 (file):
file failed to open for writing (No such file or directory):

/Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
CMakeLists.txt:2 (project)

CMake Error: Could not open file for write in copy operation /Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeFiles/3.6.2/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineSystem.cmake:189 (configure_file):
configure_file Problem configuring file
Call Stack (most recent call first):
CMakeLists.txt:2 (project)

CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineCompilerId.cmake:141 (file):
file problem creating directory:
/Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeFiles/3.6.2/CompilerIdC
Call Stack (most recent call first):
/usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineCompilerId.cmake:40 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
/usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineCCompiler.cmake:121 (CMAKE_DETERMINE_COMPILER_ID)
CMakeLists.txt:2 (project)

-- The C compiler identification is unknown
CMake Error: Could not open file for write in copy operation /Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeFiles/3.6.2/CMakeCCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineCCompiler.cmake:184 (configure_file):
configure_file Problem configuring file
Call Stack (most recent call first):
CMakeLists.txt:2 (project)

CMake Error: Could not find cmake module file: /Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeFiles/3.6.2/CMakeCCompiler.cmake
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineCompilerId.cmake:141 (file):
file problem creating directory:
/Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeFiles/3.6.2/CompilerIdCXX
Call Stack (most recent call first):
/usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineCompilerId.cmake:40 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
/usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:113 (CMAKE_DETERMINE_COMPILER_ID)
CMakeLists.txt:2 (project)

-- The CXX compiler identification is unknown
CMake Error: Could not open file for write in copy operation /Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeFiles/3.6.2/CMakeCXXCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:179 (configure_file):
configure_file Problem configuring file
Call Stack (most recent call first):
CMakeLists.txt:2 (project)

CMake Error: Could not find cmake module file: /Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeFiles/3.6.2/CMakeCXXCompiler.cmake
CMake Error at CMakeLists.txt:2 (project):
No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:2 (project):
No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: /Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. /Users/zewenhuang/Desktop/UW/CS488/Practise/Glitter/Build/CMakeCache.txt
CMake Error: : System Error: Permission denied

**Comment by robstolarz** [comment]
I'm no Polytonic, but please double-check that your disk is not full and that you have permission to write to those folders. If nothing else works, try using "Verify Disk" in Disk Utility.

I don't know why you're getting ENOENTs, that is very odd to me. Perhaps a folder needs to be created?

**Comment by Polytonic** [comment]
> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown

Do you have a compiler installed? If you're trying to use Xcode, you may need to run Xcode at least once prior to running `cmake` to accept the license agreement.

**Comment by hurrymomo** [comment]
Yes I have.I solved it by typing sudo cmake -G "Xcode"
thanks guys

**Comment by Polytonic** [comment]
I'm going to close this for now. If you have any further questions, feel free to reopen this issue, or create a new one as needed.
