### ISSUE TITLE
No Visual Studio project created by CMake

### ISSUE THREAD

**Issue by Rocketmagnet** [Polytonic/Glitter#34]
I unzipped Glitter, and ran Cmake according to the instructions in the Readme. But it produced the following error:

CMake Error at CMakeLists.txt:7 (add_subdirectory):
  The source directory

    C:/Users/User/Downloads/Glitter-master/Glitter/Vendor/glfw

  does not contain a CMakeLists.txt file.

And two similar errors.
I am using Windows 10, on a 64-bit machine, with Visual Studio 2015 Update 1.

**Comment by Polytonic** [comment]
The preferred mechanism for downloading Glitter is using `git clone` with the `--recursive` flag. 

>Start by cloning this repository, making sure to pass the --recursive flag to grab all the dependencies. If you forgot, then you can git submodule update --init instead.

Try again with the instructions in the readme and let me know if it's still broken for you?

**Comment by Polytonic** [comment]
It's been a week with no response, so I'm going to go ahead and close this. If you continue to have problems, feel free to reopen this issue.
