### ISSUE TITLE
Shader class linking problem

### ISSUE THREAD

**Issue by jaquino94** [Polytonic/Glitter#36]
Hello, 
I've run into a little problem where I can't link the Shader class that we created from the tutorial. I made my own Shader class, but I can't seem to find a way to link it to be able to use the functions from the class. I have followed everything exactly from the LearnOpenGL tutorial, but a little confused on where I was supposed to save the header file. 

UPDATE: I was able to fix the issue and it has compiled with the shader class! 
Thank you,
Justin A

**Comment by Polytonic** [comment]
Hey there; glad to hear you fixed the problem. If you have any more issues, feel free to reopen this. 😃
