### ISSUE TITLE
cmake build wrong

### ISSUE THREAD

**Issue by thrt520asd** [Polytonic/Glitter#38]
hello! thank you for you project 
but when i build your project error happens 
here is the  mistakes , by the way i use vs2017 and cmake 3.10
C:\Users\Administrator\Desktop\Glitter-master>cmake -G "Visual Studio 15"
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 6.1.7601.
-- The C compiler identification is MSVC 19.11.25547.0
-- The CXX compiler identification is MSVC 19.11.25547.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:7 (add_subdirectory):
  The source directory

    C:/Users/Administrator/Desktop/Glitter-master/Glitter/Vendor/glfw

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:12 (add_subdirectory):
  The source directory

    C:/Users/Administrator/Desktop/Glitter-master/Glitter/Vendor/assimp

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:19 (add_subdirectory):
  The source directory

    C:/Users/Administrator/Desktop/Glitter-master/Glitter/Vendor/bullet

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/Desktop/Glitter-master/CMakeFiles/CMakeOutput.l
og".
thank you very much

**Comment by Polytonic** [comment]
Hi there! Did you remember to pass the `--recursive` flag when you first cloned the repository? If not, you can fix your repository by running `git submodule update --init` at the root of the repository.

Let me know if that fixes your problem, or if you continue to have issues.

**Comment by Polytonic** [comment]
As this has been opened for 8+ days now with no response, I'm going to go ahead and mark this as closed for now. Feel free to reopen if you continue to have issues.
