### ISSUE TITLE
Doesn't compile in Windows, when using non-MS compiler

### ISSUE THREAD

**Issue by metiulekm** [Polytonic/Glitter#4]
Hi,

I wanted to try out OpenGL in Windows, with MinGW 5.1.0. However, I got the following error:

    G__~1.EXE: error: /W4: No such file or directory

Obviously, the problem is that you're checking in CMakeLists for Windows platform (`WIN32`) and not MS compiler (`MSVC`). The only thing I didn't know is what I should do with the `dl` lib, so I didn't really try to correct this.

Also, it has to be said that your project is very useful for game programming newbies like me, great job! :)

**Comment by Polytonic** [comment]
I figured most people would just download Visual Studio. Alas, it seems my laziness has finally caught up to me.  You are correct in that I only check against platform, not compiler.  

The `libdl` requirement comes from the OpenGL function loader (see [glad#Generators](https://github.com/Dav1dde/glad#cc)). I've never tried to compile under the MinGW environment, so I have no idea if you need it under your specific configuration.

**Comment by metiulekm** [comment]
Yeah, indeed. `libdl` isn't needed for Windows, as it is Unixes-only thing, so one has to check for `NOT WIN32` I think. Thanks.

And I got a lot funnier errors out of laziness before :)

**Comment by Polytonic** [comment]
Okay I've let this one sit for longer than I should have.  

I'm going to close this for now in favor of simplicity rather than perfect compatibility across compilers and platforms. If you feel strongly about supporting MinGW, I'm open to persuasive arguments otherwise.

**Comment by metiulekm** [comment]
It's your project and your decision, obviously, so go on :smile:

**Comment by Polytonic** [comment]
I changed my mind.  :smile:

**Comment by metiulekm** [comment]
Well that's interesting :smile: BTW, you may want to see how does the variable [`CXX_STANDARD`](http://www.cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html) for setting C++11 works. Except that for some reason when I tried using it, CMake simply ignored it, even when I set [`CXX_STANDARD_REQUIRED`](http://www.cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD_REQUIRED.html), so I still don't know how does that work... :worried:

**Comment by Polytonic** [comment]
I tried `CXX_STANDARD`, but I don't want to leave people inadvertently scratching their heads because they were on cmake `3.0.0` when said variable is in `3.1.3`.

**Comment by metiulekm** [comment]
Oh, that's what you want. Ok then. I didn't even know it was added so lately...

**Comment by metiulekm** [comment]
Oh. I actually tried to compile the new version, and I found some "fun" things:
1. As I mentioned, `libdl` isn't needed in Windows. Now I learned it simply isn't there, as it's Unix-only library, so I needed to add another `if`.
2. For some reason, in my configuration, `M_PI` and `M_PI_2` aren't defined, which causes Assimp to not compile. The exact error:
```
In file included from C:\Users\Mateusz\Dropbox\Programowanie\Glitter\Glitter\Vendor\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc:35:0:
C:/Users/Mateusz/Dropbox/Programowanie/Glitter/Glitter/Vendor/assimp/contrib/poly2tri/poly2tri/common/utils.h:43:29: error: 'M_PI' was not declared in this scope
 const double PI_3div4 = 3 * M_PI / 4;
                             ^
C:\Users\Mateusz\Dropbox\Programowanie\Glitter\Glitter\Vendor\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc: In member function 'void p2t::Sweep::FillAdvancingFront(p2t::SweepContext&, p2t::Node&)':
C:\Users\Mateusz\Dropbox\Programowanie\Glitter\Glitter\Vendor\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc:234:17: error: 'M_PI_2' was not declared in this scope
     if (angle > M_PI_2 || angle < -M_PI_2) break;
                 ^
C:\Users\Mateusz\Dropbox\Programowanie\Glitter\Glitter\Vendor\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc:244:17: error: 'M_PI_2' was not declared in this scope
     if (angle > M_PI_2 || angle < -M_PI_2) break;
                 ^
Glitter\Vendor\assimp\code\CMakeFiles\assimp.dir\build.make:3937: recipe for target 'Glitter/Vendor/assimp/code/CMakeFiles/assimp.dir/__/contrib/poly2tri/poly2tri/sweep/sweep.cc.obj' failed
```
I used the simple way of adding `add_definitions` in CMakeLists to fix that. `M_PI` indeed isn't defined in C++ standard, but it is Assimp fault it's used...
3. Also, with current configuration the user gets like 80 warnings while compiling Assimp. Again, it's obviously not your fault, but you can make this at least slightly better looking by moving that warnings-and-C++11-setting block below, just before including Glitter's directories. This way, there's only one warning. Also, for some reason, moving `-std=c++1y` in this way removes the error I mentioned.

So, finally I placed this
```
if(MSVC)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W4")
else()
    set(CMAKE_CXX_FLAGS "-Wall -Wextra -Wpedantic -std=c++1y")
    if(NOT WIN32)
        set(GLAD_LIBRARIES dl)
    endif()
endif()
```
beetween
```
add_subdirectory(Glitter/Vendor/assimp)
```
and
```
include_directories(Glitter/Headers/
```
and it compiled cleanly, with 3 warnings (one from Assimp, two from not using `argc` and `argv` which are indeed useless right now). Now I feel confused :smiley: Setting up the compiler can indeed be frustrating!

**Comment by Polytonic** [comment]
I built in Windows 10 with `libdl` and no problems. What version of Windows are you on? I can add more if blocks if needed.

`M_PI` sounds like a problem that needs to be raised with assimp. I'm not sure what the deal is with that.

gcc5 is a *very new* compiler revision, so I haven't had a chance to use it (on any platform).

**Comment by metiulekm** [comment]
I use 8.1 and can't update, as I don't have a lot of disk space (SSD, and no HDD for now :smiley:).

gcc5 is indeed new, I got my version from [mingw-w64 project](http://mingw-w64.org/doku.php).

And `M_PI`... Well, indeed. As I mentioned, these are defined in default mode but not when `-std=C++1y` is set, so probably they are some sort of "extension" that never was standard, but so many people used it that it became de facto standard and defined everywhere. And new compilers started to not define it beacuse they wanted to be actually C++11 conformant, and... this happened. This kind of things seem actually quite common. I think compiling Assimp without `-std=C++1y` by moving the block with it below it is actually a quite good and simple solution, as this also removes the warnings in Assimp which may confuse some people who try to only learn OpenGL.

**Comment by Polytonic** [comment]
Okay I dropped to `std=c++11` and reordered the flags. Give it a try now?

**Comment by metiulekm** [comment]
Now it indeed does work correctly on my build. I hope other builds didn't break :smiley:

**Comment by Polytonic** [comment]
Seems to be working on all my test machines.  Closing this for now.
