### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by yurivict** [Polytonic/Glitter#40]
```
tmp/Glitter/Glitter/Vendor/assimp/code/glTFExporter.cpp:585:35: error: ordered comparison between pointer and zero ('aiVector3D *' (aka 'aiVector3t<float> *') and 'int')
                if(comp_allow && (aim->mNormals > 0)) idx_srcdata_normal = b->byteLength;// Store index of normals array.
                                  ~~~~~~~~~~~~~ ^ ~
```

You shouldn't bundle packages, because now you own their build problems. assimp provides .cmake file and is actually installed on my system.

clang-40 on FreeBSD.

**Comment by Polytonic** [comment]
Hi there! Thanks for the feedback. 

Are you still experiencing this build failure?

**Comment by yurivict** [comment]
I had to update bundled dependencies to the latest version for it to go away.

**Comment by Polytonic** [comment]
Sounds like you've fixed your problem, so I'll go ahead and close this issue for now. Feel free to reopen or open a new issue if you continue to have problems. 

For what it's worth, I periodically go through and update the bundled dependencies. It sounds like I need to bump the versions again. I appreciate the data point!

**Comment by yurivict** [comment]
You need to update revisions of modues. Otherwise it doesn't build out of the box.
