### ISSUE TITLE
Shown only the gray window

### ISSUE THREAD

**Issue by yurivict** [Polytonic/Glitter#41]
FreeBSD 11.1
```
$ ./Glitter 
OpenGL 4.0.0 NVIDIA 384.59
```

**Comment by Polytonic** [comment]
Hi there! Could you go into more detail with regards to the issue you are experiencing?

**Comment by yurivict** [comment]
It only shows the gray window, nothing in it.

**Comment by Polytonic** [comment]
What did you expect to see?

>If you compile and run, you should now be at the same point as the Hello Window or Context Creation sections of the tutorials. Open main.cpp on your computer and start writing code!

If you follow the rest of the LearnOpenGL tutorial, you'll eventually generate the model shown in the screenshot, or you can follow along with my reference implementation provided in the samples folder.

**Comment by Polytonic** [comment]
I'm going to go ahead and close this for now, as it seems there was some confusion with regards to what should appear on screen. If you continue to have issues, feel free to open a new issue or reopen this one.
