### ISSUE TITLE
[Mac OS 10.13.2 / Xcode 9.1] Month 13 is out of bounds OpenGL 4.1 INTEL-10.30.12

### ISSUE THREAD

**Issue by iaomw** [Polytonic/Glitter#43]
Only gray screen, I don't know what is that. Are you trying to check the date somewhere?

2017-12-23 22:29:28.157798+0100 Glitter[15128:381747] Month 13 is out of bounds
OpenGL 4.1 INTEL-10.30.12

And, it doesn't compile with the condition below. Should be (**_!= 0_**) or (_**> (void \*)0**_)
**_if(comp_allow && (aim->mNormals > 0))_**

**Comment by Polytonic** [comment]
Hi there! What's the problem you're experiencing? Can you provide the full stack trace? 

`if(comp_allow && (aim->mNormals > 0))`

This looks like your own project code, no?

**Comment by Polytonic** [comment]
Closing this, as the original poster has not responded in over a month. Feel free to reopen if you continue to have issues.

**Comment by iaomw** [comment]
Thanks, it disappeared on Xcode 9.3. Forgot to follow this.
