### ISSUE TITLE
Unresolved External Symbols

### ISSUE THREAD

**Issue by ohunter** [Polytonic/Glitter#44]
When trying to compile the main.cpp provided in sources, I am presented with the following output:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4305	'argument': truncation from 'double' to 'const btScalar'	Glitter_test	\glitter\vendor\bullet\src\linearmath\btidebugdraw.h	169	
Warning	C4305	'argument': truncation from 'double' to 'const btScalar'	Glitter_test	\glitter\vendor\bullet\src\linearmath\btidebugdraw.h	170	
Warning	C4305	'argument': truncation from 'double' to 'const btScalar'	Glitter_test	\glitter\vendor\bullet\src\linearmath\btidebugdraw.h	171	
Warning	C4067	unexpected tokens following preprocessor directive - expected a newline	Glitter_test	\glitter\headers\glitter.hpp	20	
Error	LNK2019	unresolved external symbol _gladLoadGL referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2019	unresolved external symbol _glfwInit referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2019	unresolved external symbol _glfwTerminate referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2019	unresolved external symbol _glfwWindowHint referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2019	unresolved external symbol _glfwCreateWindow referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2019	unresolved external symbol _glfwWindowShouldClose referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2019	unresolved external symbol _glfwSetWindowShouldClose referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2019	unresolved external symbol _glfwPollEvents referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2019	unresolved external symbol _glfwGetKey referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2019	unresolved external symbol _glfwMakeContextCurrent referenced in function _main	Glitter_test	Cmain.obj	1	
Error	LNK2019	unresolved external symbol _glfwSwapBuffers referenced in function _main	Glitter_test	main.obj	1	
Error	LNK2001	unresolved external symbol _glad_glClear	Glitter_test	main.obj	1	
Error	LNK2001	unresolved external symbol _glad_glClearColor	Glitter_test	main.obj	1	
Error	LNK2001	unresolved external symbol _glad_glGetString	Glitter_test	main.obj	1	
Error	LNK1120	14 unresolved externals	Glitter_test	Glitter_test.exe	1

Compiler is built-in from Visual Studio 15 2017

**Comment by Polytonic** [comment]
Mmm, I'm guessing you figured out whatever the problem was?

**Comment by ohunter** [comment]
I think so, it seemed like my cmake didn't produce the right output, as such I'll rebuild and try again. If not, I'll reopen I guess.
