### ISSUE TITLE
"Too many sections" error on windows mingw gcc

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [Polytonic/Glitter#50]
I am trying to compile Glitter on windows using mingw gcc compiler.
It gives "Too many sections" error.

Result of `gcc --version`:
gcc.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0

**Comment by Polytonic** [comment]
You might try the suggestions on [StackOverflow](https://stackoverflow.com/questions/16596876/object-file-has-too-many-sections) for this? 

I'm afraid I don't personally build using GCC under Windows environments. Let me know if the above compiler flags work for you.

**Comment by ShivanshuKantPrasad** [comment]
I don't know how cmake works.
So i tried adding `SET(GCC_COVERAGE_COMPILE_FLAGS "-Wa,-mbig-obj")` to the end of cmake file like this but that didn't work.
Can you explain how to add flags.

**Comment by Polytonic** [comment]
> I don't know how cmake works.

You can add compiler flags [under the appropriate section](https://github.com/Polytonic/Glitter/blob/master/CMakeLists.txt#L24) in `CMakeLists.txt`.

You might also find this StackOverflow post instructive: https://stackoverflow.com/questions/11783932/

Let me know if you're still encountering this issue.

**Comment by Polytonic** [comment]
Hi there -- just checking in to see if you've resolved this? If not, let me know, otherwise I'll close this ticket sometime tomorrow.

**Comment by ShivanshuKantPrasad** [comment]
I was not able to solve this issue, but i have moved to Linux so i don't care anymore.

**Comment by Polytonic** [comment]
Alrighty, then. I'm going to go ahead and close this for now. If you continue to experience issues, feel free to reopen or open a new ticket.
