### ISSUE TITLE
How to resuse the Glitter project setting?

### ISSUE THREAD

**Issue by Jack12xl** [Polytonic/Glitter#61]
To get this straight, I mean if I wanna create a new opengl project, how to reuse the setting and dependency of Glitter?

For example, after I implement the HelloWindow tutorial (LearnOpenGL) in the [main.cpp](https://github.com/Polytonic/Glitter/blob/master/Glitter/Sources/main.cpp), here I wanna try the HelloTriangle tutorial. But instead of wiping out the former main.cpp file, here I wanna write a brand new main.cpp file for the HelloWindow, which implicitly leads to creating a new project. 
To avoid reconfiguring all the dependency again myself, (which is quite tricky and that's the reason why this repositry is helpful), I wonder what's the most widely accepted way to reuse the Glitter project's setting, along with the [Vendor](https://github.com/Polytonic/Glitter/tree/master/Glitter/Vendor) and [Header](https://github.com/Polytonic/Glitter/tree/master/Glitter/Headers).

To be more specific, I use the visual studio 2019. [This suggestions](https://docs.microsoft.com/en-us/cpp/build/create-reusable-property-configurations?view=vs-2019) using project sheet. But it seems not add the header and vendor as expected. 

Hope I make my question clear.

**Comment by Polytonic** [comment]
I'm not sure I understand your question. If you want to create a new project, you could simply clone the repository again? (or perhaps [git-worktree](https://git-scm.com/docs/git-worktree) if you wish to preserve history). You could also create a new branch, or perhaps wire up some keyboard shortcuts to load a different scene.

I don't think this is Glitter-specific, as it seems more "generic programming" related. I'm going to close this for now. If you feel that the above does not adequately satisfy your question, feel free to reopen.
