### ISSUE TITLE
Nothing displays when run on MacOS

### ISSUE THREAD

**Issue by zinwalin** [Polytonic/Glitter#62]
![image](https://user-images.githubusercontent.com/5416196/76374943-8a451100-637f-11ea-8176-e82692f0ba0e.png)

**Comment by git4paulqu** [comment]
![image](https://user-images.githubuserconte
I remember there was an example that could render this model
But I can't find the file of this model now. Where can I find this fbx?nt.com/33974362/78106881-f36fef80-7426-11ea-84e2-9fd262d7556f.png)
