### ISSUE TITLE
Feature request: add imgui

### ISSUE THREAD

**Issue by ZelCloud** [Polytonic/Glitter#67]
This is a super nice boilerplate, but one thing that might be nice to add is imgui (docking branch) to easily and quickly create menus and have ways to interact with what you're working on.

**Comment by Polytonic** [comment]
Mm, to be upfront, I've used ImGui on projects in the past, and I can't say I'm a huge fan. It's unlikely I'll add it in, but you're always welcome to add it into your own fork!
