### ISSUE TITLE
Makefile:4: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by thismakesmehappy** [Polytonic/Glitter#74]
After I run:

cmake -G "Xcode" ..

I run:
make cmake_install.cmake

and I get:
Makefile:4: *** missing separator.  Stop.

Please advise.

**Comment by Polytonic** [comment]
If you're using Xcode, why not build from Xcode ...?

**Comment by thismakesmehappy** [comment]
It's still giving me issues. I think it's a Big Sur issue.
