### ISSUE TITLE
Hi there! Could you provide some more details on which Mac you're building on, which version of Xcode you're using, and the build output produced when your build fails?

### ISSUE THREAD

**Issue by Eldeloro1** [Polytonic/Glitter#76]
Hi there! Could you provide some more details on which Mac you're building on, which version of Xcode you're using, and the build output produced when your build fails?

I've been tracking down another assimp related build issue, so you're probably not alone on this one.

_Originally posted by @Polytonic in https://github.com/Polytonic/Glitter/issues/37#issuecomment-345494502_

**Comment by Polytonic** [comment]
This seems to be a direct copy of my original comment. 🤔
